### ISSUE TITLE
Why doesn't the browser show anything?

### ISSUE THREAD

**Issue by RunningXJ** [openwisp/django-netjsongraph#96] opened 2019-06-17 11:29 UTC
I am not familiar with diango. After I deployed a django project, I made the following configuration:
INSTALLED_APPS = [
     # other apps
     'rest_framework',
     'openwisp_utils.admin_theme',
     'django_netjsongraph'
     # ...
]

From django.conf.urls import include, url

From django_netjsongraph.api import urls as netjsongraph_api
From django_netjsongraph.visualizer import urls as netjsongraph_visualizer

Urlpatterns = [
     # your URLs ...
     Url(r'^api/', include(netjsongraph_api)),
     Url(r'', include(netjsongraph_visualizer)),
]

./manage.py migrate

Open this application but can't see the display of the topology map. Do I need another configuration?

**Comment by nemesisdesign** [comment] 2020-02-26 16:33
go to /admin, create a Topology, import the data (using fetch or receive) and then click on "view topology graph" in upper right corner. Feel free to ask more questions. I close this because we use this as a bug tracker and this is not a bug report.

**Closed by nemesisdesign** 2020-02-26 16:33 UTC
